config/routes.rb
Photoapp::Application.routes.draw do
  
  get "homes/show"

  devise_for :users, controllers: {registrations: :registrations}# additional route to create the user show page -TM
  resources :users, :only => [:show, :index, :destroy, :update] do
    get 'page/:page', action: :index, on: :collection
  end

  resources :ratings

  resources :comments

  resources :tags, path_names: { new: "create", edit: "change", destroy: "remove"}

  resources :index, :only => [:show, :index]

  root :to => 'index#show'

  resources :albums do 
    resources :photos 
  end

end

app/models/rating.rb
class Rating < ActiveRecord::Base

  belongs_to :user
  belongs_to :photo

  attr_accessible :photo_id, :status, :user_id
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  # before_filter :authenticate_user!
  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ratings }
    end
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
    @rating = Rating.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/new
  # GET /ratings/new.json
  def new
    @rating = Rating.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rating }
    end
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
  end

  # POST /ratings
  # POST /ratings.json
  def create
    # we need to receive the status of the raating , like or dislike
    @rating = current_user.ratings.new(params[:rating])

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render json: @rating, status: :created, location: @rating }
      else
        format.html { render action: "new" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ratings/1
  # PUT /ratings/1.json
  def update
    @rating = Rating.find(params[:id])

    respond_to do |format|
      if @rating.update_attributes(params[:rating])
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy

    @rating = Rating.find(params[:id])
    @rating.destroy

    respond_to do |format|
      format.html { redirect_to ratings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.haml
= form_for @rating do |f|
  - if @rating.errors.any?
    #error_explanation
      %h2= "#{pluralize(@rating.errors.count, "error")} prohibited this rating from being saved:"
      %ul
        - @rating.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :photo_id
    = f.number_field :photo_id
  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions
    = f.submit 'Save'

app/views/ratings/edit.html.haml
%h1 Editing rating

= render 'form'

= link_to 'Show', @rating
\|
= link_to 'Back', ratings_path

app/views/ratings/index.html.haml
%h1 Listing ratings

%table
  %tr
    %th Status
    %th Photo
    %th User
    %th
    %th
    %th

  - @ratings.each do |rating|
    %tr
      %td= rating.status
      %td= rating.photo_id
      %td= rating.user_id
      %td= link_to 'Show', rating
      %td= link_to 'Edit', edit_rating_path(rating)
      %td= link_to 'Destroy', rating, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Rating', new_rating_path

app/views/ratings/new.html.haml
%h1 New rating

= render 'form'

= link_to 'Back', ratings_path

app/views/ratings/show.html.haml
%p#notice= notice

%p
  %b Status:
  = @rating.status
%p
  %b Photo:
  = @rating.photo_id
%p
  %b User:
  = @rating.user_id

= link_to 'Edit', edit_rating_path(@rating)
\|
= link_to 'Back', ratings_path