config/routes.rb
Photoapp::Application.routes.draw do
  
  get "homes/show"

  devise_for :users, controllers: {registrations: :registrations}# additional route to create the user show page -TM
  resources :users, :only => [:show, :index, :destroy, :update] do
    get 'page/:page', action: :index, on: :collection
  end

  resources :ratings

  resources :comments

  resources :tags, path_names: { new: "create", edit: "change", destroy: "remove"}

  resources :index, :only => [:show, :index]

  root :to => 'index#show'

  resources :albums do 
    resources :photos 
  end

end

app/models/album.rb
class Album < ActiveRecord::Base

  belongs_to :user
  has_many :photos

  attr_accessible :description, :name, :user_id

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # before_filter :authenticate_user!

  # GET /albums
  # GET /albums.json
  def index
    # PK: Check out the application controller for the method for this.
    @user = User.all
    @album = Album.order(:name).page(params[:page])
    # @album = Album.find(params[:id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])
    @photos = @album.photos
    @photo = Photo.all


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new
    @photos = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
    authorize! :edit, @album
    @photo = Photo.all
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.new(params[:album])
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])
    @photo = Photo.all

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    authorize! :destroy, @album
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.haml
= form_for @album do |f|
  - if @album.errors.any?
    #error_explanation
      %h2= "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
      %ul
        - @album.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id, if current_user.present? then "#{current_user.name}" else "Unregistered Member" end
    = f.hidden_field :user_id
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .submit  
    = f.submit

/ = form_for @photos do |f|
/   #uploader
/     = f.label :image
/     = f.file_field :image

/ AW not sure why not working 

app/views/albums/edit.html.haml
#album_text
  %h1 Edit album

.index
  #index_element
    = render 'form'

    = link_to 'Show', @album
    \|
    = link_to 'Back', albums_path

app/views/albums/index.html.haml
#album_text
  %h1 Current Albums


#random_image
  - @albums.each do |album|
    .image_info
      %h3= album.name
      - if album.photos.present?
        = link_to (image_tag album.photos.first.image), album
        %br
      = album.description
      %br
      = album.photos.count
      = "Photos"
      %br
      = link_to 'Edit', edit_album_path(album) if can? :edit, album
      = link_to '- Destroy', album, :method => :delete, :confirm => 'Are you sure?' if can? :destroy, album

= paginate @albums

app/views/albums/new.html.haml
%br
#album_text
  %h1 New album

  = render 'form'

  = link_to 'Back', albums_path

app/views/albums/show.html.haml
/ %p#notice= notice

#album_text
  %ul
    %li=@album.name    
    %i=@album.description
    %br
  \
  = link_to 'Upload Photos', new_album_photo_path(@album) if can? :edit, @album
  \
  = link_to ' - Edit', edit_album_path(@album) if can? :edit, @album
  \
  = link_to ' - Back', albums_path
  \

#random_image
  - @photos.each do |photo|
    .image_info
      = link_to (image_tag photo.image), album_photo_path(@album, photo)
      %p= photo.location
      %p= photo.description